### ISSUE TITLE
Fatale error op plugin activatie

### ISSUE THREAD

**Issue by NielsTeunissen** [codeit-ninja/wordpress-wpml-deepl-auto-translator#1]
Zodra de plugin geactiveerd word in de backend krijg je een fatale error:
![Screenshot 2022-06-29 at 07 55 43](https://user-images.githubusercontent.com/86747030/176362057-5d955a3c-5de4-45e1-9bc0-90a324beab96.png)

**Comment by codeit-ninja** [comment]
De mapnaam van de plugin moet `wordpress-wpml-deepl-auto-translator-master` heten, anders gaat het fout met updaten van de plugin.

Zou je kunnen verifiëren of `/vendor/autoload.php` bestaat op de locatie?

**Comment by codeit-ninja** [comment]
@NielsTeunissen Issue zou opgelost moeten zijn, kun je het nog een keer proberen? Als het nog steeds niet werkt kun je het ticket 'heropenen'

**Comment by NielsTeunissen** [comment]
![Screenshot 2022-06-29 at 15 25 56](https://user-images.githubusercontent.com/86747030/176447665-2ddd29fa-f5c6-48cf-b426-8f152652521d.png)
PHP versie moet hoger zijn dan 8.1.0 lijkt het op, echter gaat onze PHP maar tot 8.0.7. Is het perse nodig dat de php versie 8.1.0 of hoger moet zijn?

**Comment by codeit-ninja** [comment]
Verwijder even de hele plugin en installeer opnieuw, ik heb als het goed is eerder al composer packages verwijderd die dit nodig hadden, zou je dat even kunnen proberen?

**Comment by NielsTeunissen** [comment]
Gedaan, nog steeds hetzelfde probleem.

**Comment by codeit-ninja** [comment]
Aight, kun je deze twee commands uitvoeren?

```composer update```
```composer dump-autoload```

**Comment by codeit-ninja** [comment]
2b01a5bc2c02c52bcf606f86fa82ab69ec13e05e

**Comment by NielsTeunissen** [comment]
cd naar de plugin directory en dan die 2 commands uitvoeren?

**Comment by codeit-ninja** [comment]
Yep, als dat mogelijk is en anders plugin opnieuw downloaden
