### ISSUE TITLE
Activeert, maar fatale error

### ISSUE THREAD

**Issue by NielsTeunissen** [codeit-ninja/wordpress-wpml-deepl-auto-translator#3]
![Screenshot 2022-06-29 at 17 22 52](https://user-images.githubusercontent.com/86747030/176474523-b5577e9f-5f93-4615-954a-70f9d2cd0022.png)
activeert nu wel, maar dan weer fatal error :(

**Comment by codeit-ninja** [comment]
Fixed in 6661708b20031384fd663f7427da436a3aa3e1ac

**Comment by codeit-ninja** [comment]
Gebruik wel PHP 8.0+, het lijkt er ook op dat je PHP 7 gebruikt

**Comment by NielsTeunissen** [comment]
![Screenshot 2022-06-29 at 17 50 40](https://user-images.githubusercontent.com/86747030/176480593-259056f8-2b32-45fe-a4aa-c52d758e9ab9.png)
zelfde error nogsteeds met opnieuw gedownloadde plugin

**Comment by NielsTeunissen** [comment]
![Screenshot 2022-06-29 at 17 51 07](https://user-images.githubusercontent.com/86747030/176480705-cb004065-8faf-4c0c-b07e-b290d00c181b.png)
php8+ wordt gebruikt

**Comment by codeit-ninja** [comment]
De commit was niet goed doorgekomen ^^
Kun je opnieuw proberen?

Zie da477f811aab8543a554eef123ad973511a0013d
