### ISSUE TITLE
Wederom fatale error op plugin activatie.

### ISSUE THREAD

**Issue by NielsTeunissen** [codeit-ninja/wordpress-wpml-deepl-auto-translator#8]
![Screenshot 2022-07-13 at 20 00 01](https://user-images.githubusercontent.com/86747030/178800132-2405797a-3851-42ff-9d53-86afb02a4c11.png)

**Comment by codeit-ninja** [comment]
Ik ga het project wel ff downgraden naar php 7.4, dit geeft teveel errors zo 😔

Ik zit op php 8.1 en vergeet soms terug te zetten naar 8.0

Excuus voor de errors ;)
